#!/bin/bash
#echo -n "Are you sure you want to benchmark? [y/N]"
read response
if [ "$response" == "y" ]; then
    for i in `seq 1 20`; do
        echo "Running iteration $i"
        
    done
else
    echo "Not running benchmark."
fi
