#!/bin/bash
python makeData.py 500 500 .008 1000 classifiertest2/random/ 0
python makeData.py 500 500 .008 1000 classifiertest2/simplicial/ 1
# <networks> <neurons> <percent connectivity> <timesteps> <prefix> <simplex/not>
