#!/usr/bin/python
from subprocess import call
import sys
if len(sys.argv) < 2:
    print("Please provide a commit message")
    exit()

call(['git', 'add', '.'])
call(['git', 'commit', '-m', '"' + sys.argv[1] + '"'])
call(['git', 'push'])
