#!/usr/bin/python3
import sys, os
from model.scripts import matVis as matVis
import numpy as np

def wbVis(prefix, outdir = None):
    w0 = np.loadtxt(prefix + "l0.weights", delimiter=',')
    w1in = np.loadtxt(prefix + "l1in.weights", delimiter=',')
    w1out = np.loadtxt(prefix + "l1out.weights", delimiter=',')
    w1f = np.loadtxt(prefix + "l1f.weights", delimiter=',')
    w2in = np.loadtxt(prefix + "l2in.weights", delimiter=',')
    w2out = np.loadtxt(prefix + "l2out.weights", delimiter=',')
    w2f = np.loadtxt(prefix + "l2f.weights", delimiter=',')
    wf = np.loadtxt(prefix + "final.weights", delimiter=',')
    b0 = np.loadtxt(prefix + "l0.biases", delimiter=',')
    b1 = np.loadtxt(prefix + "l1.biases", delimiter=',')
    b2 = np.loadtxt(prefix + "l2.biases", delimiter=',')
    if outdir is not None:
        fullOut = outdir + "weights/"
        if not os.path.exists(outdir):
            os.mkdir(outdir)
            os.mkdir(fullOut)
        elif not os.path.exists(fullOut):
            os.mkdir(fullOut)
        matVis(w0, fullOut + "w0.png")
        matVis(w1in, fullOut + "w1in.png")
        matVis(w1out, fullOut + "w1out.png")
        matVis(w1f, fullOut + "w1f.png")
        matVis(w2in, fullOut + "w2in.png")
        matVis(w2out, fullOut + "w2out.png")
        matVis(w2f, fullOut + "w2f.png")
        matVis(np.expand_dims(wf, 1), fullOut + "final.png")
        matVis(np.expand_dims(b0, 1), fullOut + "b0.png")
        matVis(np.expand_dims(b1, 1) , fullOut + "b1.png")
        matVis(np.expand_dims(b2, 1) , fullOut + "b2.png")
    



if len(sys.argv) < 2:
    print("Usage: visualize.py <runId>\n\tstruct <dataId>\n\tmats <runId>")
    sys.exit()
if len(sys.argv) > 2:
    if sys.argv[1] == "struct":
        struct = np.loadtxt("dataStaging/" + sys.argv[2] + "/struct.csv", delimiter=',')
        matVis(struct, "dataStaging/" + sys.argv[2] + "/struct.png", connections=True)
        sys.exit()
    elif sys.argv[1] == "mats":
        wbVis("model/checkpoints/" + sys.argv[2] + "/mats/", 
                "visData/" + sys.argv[2] + "/")
        sys.exit()

runId = sys.argv[1]
if not os.path.exists("visData/" + runId):
    print("data not found")
    sys.exit()

visDir = "visData/" + runId + "/"

inData = np.loadtxt(visDir + "input", delimiter=',')
out0 = np.loadtxt(visDir + "out0", delimiter=',')
out1 = np.loadtxt(visDir + "out1", delimiter=',')
out2 = np.loadtxt(visDir + "out2", delimiter=',')
outf = np.expand_dims(np.loadtxt(visDir + "outf", delimiter=','), 0)
pred = np.expand_dims(np.loadtxt(visDir + "pred", delimiter=','), 0)

outf = outf.reshape((inData.shape[1], inData.shape[1]))
pred = pred.reshape((inData.shape[1], inData.shape[1]))

n = 6
matVis(inData, visDir + "input.png")
matVis(out0, visDir + "out0.png", connections=True, n=n)
matVis(out1, visDir + "out1.png", connections=True, n=n)
matVis(out1, visDir + "out2.png", connections=True, n=n)
matVis(outf, visDir + "outf.png", connections=True)
matVis(pred, visDir + "pred.png", connections=True)
