#!/usr/bin/python3
import numpy as np
import sys

if not len(sys.argv) == 2:
    print("Usage: termStructVis <struct>")
    exit()

struct = np.loadtxt(sys.argv[1], delimiter=',')

n = struct.shape[0]
print(" " + "-"*(n+2))
for i in range(n):
    print(i,"|" + "".join([("#" if x > 0 else " ") for x in struct[i]]) + "|")
print(" " + "-"*(n+2))

